channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy=1.23
  - faiss-cpu=1.6.5
  - umap-learn
  - fbpca
  - opentsne
  - matplotlib
  - seaborn
  - hdf5storage
  - numba=0.55.1
  - scikit-image
  - cython
  - pandas
  - ffmpeg=
