label: 'fitsne'

analysis: 'embed'

downsample: 5

column: 'Condition'
density_by_column: ['id']

filter_still: False

single_embed:
  method: 'fitsne'
  perplexity: 50
  lr: 'auto'
  sigma: 17

transform_embed: 
  method: 'knn'
  k: 5
  sigma: 15
  
skeleton_vids: False

save_embedder: True
load_embedder: null