# Folder path of data location
data_path: '/home/exx/Desktop/GitHub/CAPTURE_data/ensemble_healthy/'

# File path of predictions file
pose_path: '/home/exx/Desktop/GitHub/CAPTURE_data/ensemble_healthy/predictions.mat'

# File path of metadata file
meta_path: '/home/exx/Desktop/GitHub/CAPTURE_data/ensemble_healthy/metadata.csv'

# Output folder of all plots
out_path: '/home/exx/Desktop/GitHub/results/ensemble_healthy/'

# Path of list of behavior heuristics
heuristics_path: '/home/exx/Desktop/GitHub/dappy/src/dappy/behavior_heuristics.py'

# File path of skeletal specifications
skeleton_path: '/home/exx/Desktop/GitHub/dappy/src/dappy/skeletons.py'

# Key of skeleton in the skeletons file
skeleton_name: 'mouse20_notail'

label: 'fitsne'

analysis: 'embed'

downsample: 10

single_embed:
  method: 'fitsne'
  perplexity: 50
  lr: 'auto'
  sigma: 15

transform_embed: 
  method: 'knn'
  k: 5
  sigma: 15