# File path of analysis struct with jt_features from CAPTURE MATLAB code
analysis_path: '/home/exx/Desktop/GitHub/demo_data/myanalysisstruct.mat'

# Folder path of data location
data_path: '/home/exx/Desktop/GitHub/demo_data/'

# File path of predictions file
pose_path: '/home/exx/Desktop/GitHub/demo_data/predictions.mat'

# File path of metadata file
meta_path: '/home/exx/Desktop/GitHub/demo_data/metadata.csv'

# Output folder of all plots
out_path: '/home/exx/Desktop/GitHub/results/'

# Path of list of behavior heuristics
heuristics_path: '/home/exx/Desktop/GitHub/dappy/dappy/behavior_heuristics.py'

# File path of skeletal specifications
skeleton_path: '/home/exx/Desktop/GitHub/dappy/dappy/skeletons.py'

# Type of skeleton: 'mouse20' or 'mouse22'
skeleton_name: 'mouse20_notail'

# variable in predictions file to split by into batches
exp_key: 'recordingID'